services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_DB: stats_db
      POSTGRES_USER: stats_user
      POSTGRES_PASSWORD: stats_password
    ports:
      - "5432:5432"
    volumes:
      - stats-db-data:/var/lib/postgresql/data



  stats-server:
      build:
        context: .
        dockerfile: stats/stats-server/Dockerfile
      ports:
        - "9090:9090"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats_db
        SPRING_DATASOURCE_USERNAME: stats_user
        SPRING_DATASOURCE_PASSWORD: stats_password
      depends_on:
        stats-db:
          condition: service_healthy

volumes:
  stats-db-data:

#  ewm-service:
#    image: ewm-service:latest
#    container_name: ewm-service
#    ports:
#      - "8080:8080"
#    depends_on:
#      ewm-db:
#        condition: service_healthy
#
#  ewm-db:
#    image: postgres:16.1
#    container_name: ewm-db
#    environment:
#     POSTGRES_DB: ewm_db
#     POSTGRES_USER: ewm_user
#     POSTGRES_PASSWORD: ewm_password
#    healthcheck:
#      test: ["CMD-SHELL", "pgisready -U ewm_user -d ewm_db"]
#      interval: 5s
#      timeout: 5s
#      retries: 5